# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pypowerwall/tedapi/protobuf/V2026_06/tedapi_v2_transport.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'pypowerwall/tedapi/protobuf/V2026_06/tedapi_v2_transport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pypowerwall.tedapi.protobuf.V2026_06 import tedapi_v2_energy_device_pb2 as pypowerwall_dot_tedapi_dot_protobuf_dot_V2026__06_dot_tedapi__v2__energy__device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>pypowerwall/tedapi/protobuf/V2026_06/tedapi_v2_transport.proto\x12\x38pypowerwall.tedapi.protobuf.V2026_06.tedapi_v2_transport\x1a\x42pypowerwall/tedapi/protobuf/V2026_06/tedapi_v2_energy_device.proto\"\xbc\x01\n\x07Message\x12\x63\n\x07message\x18\x01 \x01(\x0b\x32R.pypowerwall.tedapi.protobuf.V2026_06.tesla.proto.energy_device.v1.MessageEnvelope\x12L\n\x04tail\x18\x02 \x01(\x0b\x32>.pypowerwall.tedapi.protobuf.V2026_06.tedapi_v2_transport.Tail\"\x15\n\x04Tail\x12\r\n\x05value\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pypowerwall.tedapi.protobuf.V2026_06.tedapi_v2_transport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=193
  _globals['_MESSAGE']._serialized_end=381
  _globals['_TAIL']._serialized_start=383
  _globals['_TAIL']._serialized_end=404
# @@protoc_insertion_point(module_scope)
