POWERWALLS = ('{"enumerating": false, "updating": false, "checking_if_offgrid": false, "running_phase_detection": '
              'false, "phase_detection_last_error": "no phase information", "bubble_shedding": false, '
              '"on_grid_check_error": "on grid check not run", "grid_qualifying": false, "grid_code_validating": '
              'false, "phase_detection_not_available": true, "powerwalls": [{"Type": "", "PackagePartNumber": '
              '"2012170-25-E", "PackageSerialNumber": "TG1234567890G1", "type": "SolarPowerwall", "grid_state": '
              '"Grid_Uncompliant", "grid_reconnection_time_seconds": 0, "under_phase_detection": false, "updating": '
              'false, "commissioning_diagnostic": {"name": "Commissioning", "category": "InternalComms", '
              '"disruptive": false, "inputs": null, "checks": [{"name": "CAN connectivity", "status": "fail", '
              '"start_time": "2023-12-16T08:34:17.3068631-08:00", "end_time": "2023-12-16T08:34:17.3068696-08:00", '
              '"message": "Cannot perform this action with site controller running. From landing page, '
              'either \\"STOP SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {}, "debug": {}, '
              '"checks": null}, {"name": "Enable switch", "status": "fail", "start_time": '
              '"2023-12-16T08:34:17.306875474-08:00", "end_time": "2023-12-16T08:34:17.306880724-08:00", '
              '"message": "Cannot perform this action with site controller running. From landing page, '
              'either \\"STOP SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {}, "debug": {}, '
              '"checks": null}, {"name": "Internal communications", "status": "fail", "start_time": '
              '"2023-12-16T08:34:17.306886099-08:00", "end_time": "2023-12-16T08:34:17.306891223-08:00", '
              '"message": "Cannot perform this action with site controller running. From landing page, '
              'either \\"STOP SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {}, "debug": {}, '
              '"checks": null}, {"name": "Firmware up-to-date", "status": "fail", "start_time": '
              '"2023-12-16T08:34:17.306896598-08:00", "end_time": "2023-12-16T08:34:17.306901723-08:00", '
              '"message": "Cannot perform this action with site controller running. From landing page, '
              'either \\"STOP SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {}, "debug": {}, '
              '"checks": null}], "alert": false}, "update_diagnostic": {"name": "Firmware Update", "category": '
              '"InternalComms", "disruptive": true, "inputs": null, "checks": [{"name": "Solar Inverter firmware", '
              '"status": "not_run", "start_time": null, "end_time": null, "progress": 0, "results": null, '
              '"debug": null, "checks": null}, {"name": "Solar Safety firmware", "status": "not_run", "start_time": '
              'null, "end_time": null, "progress": 0, "results": null, "debug": null, "checks": null}, '
              '{"name": "Grid code", "status": "not_run", "start_time": null, "end_time": null, "progress": 0, '
              '"results": null, "debug": null, "checks": null}, {"name": "Powerwall firmware", "status": "not_run", '
              '"start_time": null, "end_time": null, "progress": 0, "results": null, "debug": null, '
              '"checks": null}, {"name": "Battery firmware", "status": "not_run", "start_time": null, "end_time": '
              'null, "progress": 0, "results": null, "debug": null, "checks": null}, {"name": "Inverter firmware", '
              '"status": "not_run", "start_time": null, "end_time": null, "progress": 0, "results": null, '
              '"debug": null, "checks": null}, {"name": "Grid code", "status": "not_run", "start_time": null, '
              '"end_time": null, "progress": 0, "results": null, "debug": null, "checks": null}], "alert": false}, '
              '"bc_type": null, "in_config": true}, {"Type": "", "PackagePartNumber": "3012170-05-B", '
              '"PackageSerialNumber": "TG1234567890G1", "type": "ACPW", "grid_state": "Grid_Uncompliant", '
              '"grid_reconnection_time_seconds": 0, "under_phase_detection": false, "updating": false, '
              '"commissioning_diagnostic": {"name": "Commissioning", "category": "InternalComms", "disruptive": '
              'false, "inputs": null, "checks": [{"name": "CAN connectivity", "status": "fail", "start_time": '
              '"2023-12-16T08:34:17.320856307-08:00", "end_time": "2023-12-16T08:34:17.320940302-08:00", '
              '"message": "Cannot perform this action with site controller running. From landing page, '
              'either \\"STOP SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {}, "debug": {}, '
              '"checks": null}, {"name": "Enable switch", "status": "fail", "start_time": '
              '"2023-12-16T08:34:17.320949301-08:00", "end_time": "2023-12-16T08:34:17.320955301-08:00", '
              '"message": "Cannot perform this action with site controller running. From landing page, '
              'either \\"STOP SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {}, "debug": {}, '
              '"checks": null}, {"name": "Internal communications", "status": "fail", "start_time": '
              '"2023-12-16T08:34:17.320960676-08:00", "end_time": "2023-12-16T08:34:17.320966176-08:00", '
              '"message": "Cannot perform this action with site controller running. From landing page, '
              'either \\"STOP SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {}, "debug": {}, '
              '"checks": null}, {"name": "Firmware up-to-date", "status": "fail", "start_time": '
              '"2023-12-16T08:34:17.32097155-08:00", "end_time": "2023-12-16T08:34:17.3209768-08:00", "message": '
              '"Cannot perform this action with site controller running. From landing page, either \\"STOP '
              'SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {}, "debug": {}, "checks": null}], '
              '"alert": false}, "update_diagnostic": {"name": "Firmware Update", "category": "InternalComms", '
              '"disruptive": true, "inputs": null, "checks": [{"name": "Powerwall firmware", "status": "not_run", '
              '"start_time": null, "end_time": null, "progress": 0, "results": null, "debug": null, '
              '"checks": null}, {"name": "Battery firmware", "status": "not_run", "start_time": null, "end_time": '
              'null, "progress": 0, "results": null, "debug": null, "checks": null}, {"name": "Inverter firmware", '
              '"status": "not_run", "start_time": null, "end_time": null, "progress": 0, "results": null, '
              '"debug": null, "checks": null}, {"name": "Grid code", "status": "not_run", "start_time": null, '
              '"end_time": null, "progress": 0, "results": null, "debug": null, "checks": null}], "alert": false}, '
              '"bc_type": null, "in_config": true}], "gateway_din": "1232100-00-E--TG1234567890G1", '
              '"sync": {"updating": false, "commissioning_diagnostic": {"name": "Commissioning", "category": '
              '"InternalComms", "disruptive": false, "inputs": null, "checks": [{"name": "CAN connectivity", '
              '"status": "fail", "start_time": "2023-12-16T08:34:17.321101293-08:00", "end_time": '
              '"2023-12-16T08:34:17.321107918-08:00", "message": "Cannot perform this action with site controller '
              'running. From landing page, either \\"STOP SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {'
              '}, "debug": {}, "checks": null}, {"name": "Firmware up-to-date", "status": "fail", "start_time": '
              '"2023-12-16T08:34:17.321113792-08:00", "end_time": "2023-12-16T08:34:17.321118917-08:00", '
              '"message": "Cannot perform this action with site controller running. From landing page, '
              'either \\"STOP SYSTEM\\" or \\"RUN WIZARD\\" to proceed.", "results": {}, "debug": {}, '
              '"checks": null}], "alert": false}, "update_diagnostic": {"name": "Firmware Update", "category": '
              '"InternalComms", "disruptive": true, "inputs": null, "checks": [{"name": "Synchronizer firmware", '
              '"status": "not_run", "start_time": null, "end_time": null, "progress": 0, "results": null, '
              '"debug": null, "checks": null}, {"name": "Islanding configuration", "status": "not_run", '
              '"start_time": null, "end_time": null, "progress": 0, "results": null, "debug": null, '
              '"checks": null}, {"name": "Grid code", "status": "not_run", "start_time": null, "end_time": null, '
              '"progress": 0, "results": null, "debug": null, "checks": null}], "alert": false}}, "msa": null, '
              '"states": null}')

METERS_SITE = ('[{"id":0,"location":"site","type":"synchrometerX","cts":[true,true,false,false],'
               '"inverted":[false,false,false,false],'
               '"connection":{"short_id":"1232100-00-E--TG123456789E4G",'
               '"device_serial":"JBL12345Y1F012synchrometerX","https_conf":{}},'
               '"Cached_readings":{"last_communication_time":"2023-12-16T11:48:34.135766872-08:00",'
               '"instant_power":2495,"instant_reactive_power":-212,'
               '"instant_apparent_power":2503.9906149983867,"frequency":0,'
               '"energy_exported":4507438.170261594,"energy_imported":6995047.554439916,'
               '"instant_average_voltage":210.8945063295865,"instant_average_current":20.984,'
               '"i_a_current":13.3045,"i_b_current":7.6795,"i_c_current":0,'
               '"last_phase_voltage_communication_time":"2023-12-16T11:48:34.035339849-08:00",'
               '"v_l1n":121.72,"v_l2n":121.78,'
               '"last_phase_power_communication_time":"2023-12-16T11:48:34.135766872-08:00",'
               '"real_power_a":1584,"real_power_b":911,"reactive_power_a":-129,"reactive_power_b":-83,'
               '"last_phase_energy_communication_time":"0001-01-01T00:00:00Z",'
               '"serial_number":"JBL12345Y1F012","version":"fa0c1ad02efda3","timeout":1500000000,'
               '"instant_total_current":20.984}}]')

SOLARS_BRANDS = ('["ABB","Ablerex Electronics","Advanced Energy Industries","Advanced Solar Photonics","AE Solar '
                 'Energy","AEconversion Gmbh","AEG Power Solutions","Aero-Sharp","Afore New Energy Technology Shanghai '
                 'Co","Agepower Limit","Alpha ESS Co","Alpha Technologies","Altenergy Power System","American Electric '
                 'Technologies","AMETEK Solidstate Control","Andalay Solar","Apparent","Asian Power Devices",'
                 '"AU Optronics","Auxin Solar","Ballard Power Systems","Beacon Power","Beijing Hua Xin Liu He '
                 'Investment (Australia) Pty","Beijing Kinglong New Energy","Bergey Windpower","Beyond Building '
                 'Group","Beyond Building Systems","BYD Auto Industry Company Limited","Canadian Solar",'
                 '"Carlo Gavazzi","CFM Equipment Distributors","Changzhou Nesl Solartech","Chiconypower","Chilicon",'
                 '"Chilicon Power","Chint Power Systems America","Chint Solar Zhejiang","Concept by US",'
                 '"Connect Renewable Energy","Danfoss","Danfoss Solar","Darfon Electronics","DASS tech","Delta Energy '
                 'Systems","Destin Power","Diehl AKO Stiftung","Diehl AKO Stiftung \u0026  KG","Direct Grid '
                 'Technologies","Dow Chemical","DYNAPOWER COMPANY","E-Village Solar","EAST GROUP CO LTD","Eaton",'
                 '"Eguana Technologies","Elettronica Santerno","Eltek","Emerson Network Power","Enecsys",'
                 '"Energy Storage Australia Pty","EnluxSolar","Enphase Energy","Eoplly New Energy Technology",'
                 '"EPC Power","ET Solar Industry","ETM Electromatic","Exeltech","Flextronics Industrial","Flextronics '
                 'International USA","Fronius","FSP Group","GAF","GE Energy","Gefran","Geoprotek","Global Mainstream '
                 'Dynamic Energy Technology","Green Power Technologies","GreenVolts","GridPoint","Growatt",'
                 '"Gsmart Ningbo Energy Storage Technology Co","Guangzhou Sanjing Electric Co","Hangzhou Sunny Energy '
                 'Science and Technology Co","Hansol Technics","Hanwha Q CELLS \u0026 Advanced Materials Corporation",'
                 '"Heart Transverter","Helios","HiQ Solar","HiSEL Power","Home Director","Hoymiles Converter '
                 'Technology","Huawei Technologies","Huawei Technologies Co","HYOSUNG","i-Energy Corporation",'
                 '"Ideal Power","Ideal Power Converters","IMEON ENERGY","Ingeteam","Involar","INVOLAR","INVT Solar '
                 'Technology Shenzhen Co","iPower","IST Energy","Jema Energy","Jiangsu GoodWe Power Supply Technology '
                 'Co","Jiangsu Weiheng Intelligent Technology Co","Jiangsu Zeversolar New Energy","Jiangsu Zeversolar '
                 'New Energy Co","Jiangyin Hareon Power","Jinko Solar","KACO","Kehua Hengsheng Co","Kostal Solar '
                 'Electric","LeadSolar Energy","Leatec Fine Ceramics","LG Electronics","Lixma Tech","Mage Solar",'
                 '"Mage Solar USA","Mariah Power","MIL-Systems","Ming Shen Energy Technology","Mohr Power",'
                 '"Motech Industries","NeoVolta","Nextronex Energy Systems","Nidec ASI","Ningbo Ginlong Technologies",'
                 '"Ningbo Ginlong Technologies Co","Northern Electric","ONE SUN MEXICO  DE C.V.","Open Energy",'
                 '"OPTI International","OPTI-Solar","OutBack Power Technologies","Panasonic Corporation Eco Solutions '
                 'Company","Perfect Galaxy","Petra Solar","Petra Systems","Phoenixtec Power","Phono Solar Technology",'
                 '"Pika Energy","Power Electronics","Power-One","Powercom","PowerWave Energy Pty","Princeton Power '
                 'Systems","PurpleRubik New Energy Technology Co","PV Powered","Redback Technologies Limited",'
                 '"RedEarth Energy Storage Pty","REFU Elektronik","Renac Power Technology Co","Renergy",'
                 '"Renesola Zhejiang","Renovo Power Systems","Resonix","Rhombus Energy Solutions","Ritek Corporation",'
                 '"Sainty Solar","Samil Power","SanRex","SANYO","Sapphire Solar Pty","Satcon Technology",'
                 '"SatCon Technology","Schneider","Schneider Inverters USA","Schuco USA","Selectronic Australia",'
                 '"Senec GmbH","Shanghai Sermatec Energy Technology Co","Shanghai Trannergy Power Electronics Co",'
                 '"Sharp","Shenzhen BYD","Shenzhen Growatt","Shenzhen Growatt Co","Shenzhen INVT Electric Co",'
                 '"SHENZHEN KSTAR NEW ENERGY COMPANY LIMITED","Shenzhen Litto New Energy Co","Shenzhen Sinexcel '
                 'Electric","Shenzhen Sinexcel Electric Co","Shenzhen SOFARSOLAR Co","Siemens Industry",'
                 '"Silicon Energy","Sineng Electric Co","SMA","Sol-Ark","Solar Juice Pty","Solar Liberty",'
                 '"Solar Power","Solarbine","SolarBridge Technologies","SolarCity","SolarEdge Technologies",'
                 '"Solargate","Solaria Corporation","Solarmax","SolarWorld","SolaX Power Co","SolaX Power Network '
                 'Technology (Zhe jiang)","SolaX Power Network Technology Zhejiang Co","Solectria Renewables","Solis",'
                 '"Sonnen GmbH","Sonnetek","Southwest Windpower","Sparq Systems","Sputnik Engineering","STARFISH HERO '
                 'CO","Sungrow Power Supply","Sungrow Power Supply Co","Sunna Tech","SunPower","SunPower  (Original '
                 'Mfr.Fronius)","Sunset","Sustainable Energy Technologies","Sustainable Solar Services",'
                 '"Suzhou Hypontech Co","Suzhou Solarwii Micro Grid Technology Co","Sysgration","Tabuchi Electric",'
                 '"Talesun Solar","Tesla","The Trustee for Soltaro Unit Trust","TMEIC","TOPPER SUN Energy Tech",'
                 '"Toshiba International","Trannergy","Trina Energy Storage Solutions (Jiangsu)","Trina Energy Storage '
                 'Solutions Jiangsu Co","Trina Solar Co","Ubiquiti Networks International","United Renewable Energy '
                 'Co","Westinghouse Solar","Windterra Systems","Xantrex Technology","Xiamen Kehua Hengsheng",'
                 '"Xiamen Kehua Hengsheng Co","Xslent Energy Technologies","Yaskawa Solectria Solar","Yes! Solar",'
                 '"Zhongli Talesun Solar","ZIGOR","シャープ (Sharp)","パナソニック (Panasonic)","三菱電機 (Mitsubishi)",'
                 '"京セラ (Kyocera)","東芝 (Toshiba)","長州産業 (Choshu Sangyou)","ｶﾅﾃﾞｨｱﾝ  ｿｰﾗｰ"]')

METERS = ('[{"serial":"VAH1234AB1234","short_id":"73533","type":"neurio_w2_tcp","connected":true,'
          '"cts":[{"type":"solarRGM","valid":[true,false,false,false],"inverted":[false,false,false,false],'
          '"real_power_scale_factor":2}],"ip_address":"PWRview-73533","mac":"01-23-45-56-78-90"},'
          '{"serial":"JBL12345Y1F012synchrometerY","short_id":"1232100-00-E--TG123456789EGG","type":"synchrometerY"},'
          '{"serial":"JBL12345Y1F012synchrometerX","short_id":"1232100-00-E--TG123456789EGG","type":"synchrometerX",'
          '"cts":[{"type":"site","valid":[true,true,false,false],"inverted":[false,false,false,false]}]}]')

INSTALLER = ('{"company":"Tesla","customer_id":"","phone":"","email":"","location":"","mounting":"","wiring":"",'
             '"backup_configuration":"Whole Home","solar_installation":"New","solar_installation_type":"PV Panel",'
             '"run_sitemaster":true,"verified_config":true,"installation_types":["Residential"]}')

NETWORKS = ('[{"network_name":"ethernet_tesla_internal_default","interface":"EthType","enabled":true,"dhcp":true,'
            '"extra_ips":[{"ip":"192.168.90.2","netmask":24}],"active":true,"primary":true,"lastTeslaConnected":true,'
            '"lastInternetConnected":true,"iface_network_info":{"network_name":"ethernet_tesla_internal_default",'
            '"ip_networks":[{"IP":"","Mask":"////AA=="}],"gateway":"","interface":"EthType",'
            '"state":"DeviceStateReady","state_reason":"DeviceStateReasonNone","signal_strength":0,"hw_address":""}},'
            '{"network_name":"gsm_tesla_internal_default","interface":"GsmType","enabled":true,"dhcp":null,'
            '"active":true,"primary":false,"lastTeslaConnected":false,"lastInternetConnected":false,'
            '"iface_network_info":{"network_name":"gsm_tesla_internal_default","ip_networks":[{"IP":"",'
            '"Mask":"/////w=="}],"gateway":"","interface":"GsmType","state":"DeviceStateReady",'
            '"state_reason":"DeviceStateReasonNone","signal_strength":71,"hw_address":""}}]')
